

learning_rate: 0.0003

gradient_accumulation_steps: 32
epochs: 5 
device: 'auto'
use_amp: true
grad_clip: 1.0
checkpoint_dir: output/checkpoints
checkpoint_freq: 1 
log_freq: 10 
log_dir: output/logs
early_stopping_patience: 5 
batch_size: 2 